import Head from 'next/head'

import Select from 'react-select'

export default function Trips(data) {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>Trips index file</h1>
    <Select
      id='countries-select'
      instanceId='countries-select'
      options={data.countries}
    />
    </>
  )
}